server:
  port: 8086
# Enable the endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
  messages:
    basename: i18n/branch-messages,i18n/base-messages,i18n/user-management-messages
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/blubank
      client:
        provider:
          blubank:
            issuer-uri: http://localhost:8080/realms/blubank

keycloak:
  enabled: true
  auth-server-url: http://localhost:8080/auth
  realm: blubank
  resource: branch-channel
  credentials:
      secret: branch-channel-secret

logging:
  level:
    org.springframework.security: debug
    org.keycloak: debug
    org:
      springframework:
        jdbc:
          datasource: debug

